fix checkpatch warnings / errors
Run checkpatch --strict -f on code base and warnings / errors / checks.

The following is ignored, since fixing would involve massive redesign:
ERROR: Macros with complex values should be enclosed in parenthesis

The following are ignored, since proposed solution is no better:
CHECK: Alignment should match open parenthesis
+       if (pdcp_cp_fp[cipherdata->algtype][authdata->algtype](program,
+                       cipherdata,

CHECK: Alignment should match open parenthesis
+       if (pdcp_cp_fp[cipherdata->algtype][authdata->algtype](program,
+                       cipherdata,

Signed-off-by: Horia Geanta <horia.geanta@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/14186
Reviewed-by: Cristian Stoica <cristian.stoica@freescale.com>
Change-Id: Ie7062cf94a607286450d429f52fe5efedd9edf1d
Reviewed-on: http://git.am.freescale.net:8181/22725