don't use macros that expand to two parameters
IMM() and PTR() macros do not obey the Linux kernel coding style.
Similar, #defines that are used in the mechanism of hiding parameter
type from user are not allowed - checkpatch complains:
ERROR: Macros with complex values should be enclosed in parenthesis

Remove IMM(), PTR() macros and hidden parameter types
(IMM_DATA, PTR_DATA).
Replace them with IMMED, IMMED2 and COPY flags.

LOAD, FIFOLOAD and KEY commands change as follows:
-IMM(x) with or w/out IMMED flag -> IMM() removed and IMMED flag
-PTR(x) w/out IMMED flag -> PTR() removed and no flag
-PTR(x) with IMMED flag -> PTR(x) removed and IMMED and COPY flags

MOVE commands where length is provided using IMM() macro are modified
by adding the IMMED flag. This is to distinguish between MOVE and
MOVE_LEN (i.e. MOVE commands where length is provided using MATH
registers).

JUMP commands that use IMM() or PTR() macros to specify address type
don't need specialy handling (besides removing macro usage).

IMMED2 is introduced solely for MATH commands (where both operands
are allowed to be immediata data in the same time).

Signed-off-by: Horia Geanta <horia.geanta@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/14990
Reviewed-by: Alexandru Porosanu <alexandru.porosanu@freescale.com>
Change-Id: Id7c28211173b984b32b0522859ef5bb0ae1f9d0d
Reviewed-on: http://git.am.freescale.net:8181/22738