fix HMAC descriptor key length
Due to a programming error, the key length was assumed to
be equal to the truncated ICV length.
While here, also fix the statistics for HMAC processing

Signed-off-by: Alex Porosanu <alexandru.porosanu@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/15017
Reviewed-by: Horia Ioan Geanta Neag <horia.geanta@freescale.com>
Tested-by: Horia Ioan Geanta Neag <horia.geanta@freescale.com>

Integrated fix for do_icv variable assignment from commit
9a0aebfb3bb1 ("fix compilation errors in flib/desc/algo.h").

Signed-off-by: Horia Geanta <horia.geanta@freescale.com>
Change-Id: I50f266fe2ac67bff1826a43eb921c97ffe5b2f56
Reviewed-on: http://git.am.freescale.net:8181/22737