define no_printf() when pr_debug() unavailable and !RTA_DEBUG
In case compilation flags don't include at least one of SUPPRESS_PRINTS
or RTA_DEBUG, no_printf() won't be defined.

If the environment does not provide a definition for pr_debug(),
compiler will complain:

gcc -Wall -Wshadow -g -O0 -I../include   -c -o blkcipher_seq.o blkcipher_seq.c
In file included from ../include/flib/rta.h:17:0,
                 from blkcipher_seq.c:8:
../include/flib/rta/move_cmd.h: In function ‘rta_move’:
../include/flib/rta/move_cmd.h:153:5: warning: implicit declaration of function ‘no_printf’ [-Wimplicit-function-declaration]
     pr_debug("MOVE: Offset not supported by SEC Era %d. SEC PC: %d; Instr: %d\n",
     ^

While here, mark "fmt" parameter of no_printf() as unused, or else compiler
will complain when using -Wunused-parameter flag.

Reported-by: Akhil Goyal <akhil.goyal@freescale.com>
Signed-off-by: Horia Geantă <horia.geanta@freescale.com>