fix HMAC & block cipher descriptor sharing type
The best performance is achieved when SERIAL sharing
is being employed in shared descriptors. This patch
modifies the block-cipher & HMAC descriptors to use
SERIAL sharing.

Signed-off-by: Alex Porosanu <alexandru.porosanu@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/14646
Reviewed-by: Horia Ioan Geanta Neag <horia.geanta@freescale.com>
Tested-by: Horia Ioan Geanta Neag <horia.geanta@freescale.com>

Integrated fix for is_aes_dec variable declaration from commit
9a0aebfb3bb1 ("fix compilation errors in flib/desc/algo.h").

Signed-off-by: Horia Geanta <horia.geanta@freescale.com>
Change-Id: Ia7ed14ef2e2315bd0d31246917828ee429810c89
Reviewed-on: http://git.am.freescale.net:8181/22729